### PR TITLE
mod2obs with different depvar names

### PR DESCRIPTION
**Pull request by jtwhite79**
patch in mod2obs and a test for it.  Also moved to `np.asarray()` and dropped explicit `copy=False` according to numpy 2 suggestions (also pinned explicit numpy>2).  @mwtoews lemme if you think this is an ok approach (instead of `np.array()` like it is now) and also your thoughts on explicit numpy > 2 (I need this for some pyemu-ppu integration stuff).

### CODE REVIEW

**Comment by mwtoews** [comment]
Apologies for the delay @jtwhite79 currently on annual leave but I could probably find some more time to give this a better review.

Ideally this package should work with most versions of NumPy, without need to pin to any particular version.

**Comment by jtwhite79** [comment]
@mwtoews you ok to merge this in?  The reason I wanted to pin to np2 is just to make sure the tests are using np2 (for now) since that seems to be where the problems are...

**Comment by mwtoews** [comment]
I'm probably OK with most of this, but a bit confused by the commit history. The `.lst` files don't need to be added (and should be added to gitignore). I've removed the explicit `copy=False` with 9758c86d9f6d52959b4f482cee2c5149e5547aea, so these changes aren't seen here. I can't recall why I chose `np.array` but it seems that `np.asarray` is the better choice. I still don't think any pinning is necessary, as we are testing both 2.x and 1.x already. Pinning just leads to complications when integrating multiple packages.

**Comment by mwtoews** [comment]
@jtwhite79 I'll make a few adjustments to this PR then I'll merge it. I can look into making a release, perhaps later today if I can find the time.

**Comment by mwtoews** [comment]
@jtwhite79 I've made a few edits, and I'll let you hit the merge button if you are happy with them. I've remove explicit numpy version pinning since it is unnecessary, since this code is designed and tested for numpy 1.x and 2.x.

I'll hopefully get to a PR tomorrow to clean-up a few other aspects before setting a release.

**Review by mwtoews — APPROVED** [review]

**Pull request merged**
